FROM node:12-alpine

EXPOSE 5078

WORKDIR /usr/bin/app

COPY ./src ./src
COPY ./package.json ./
COPY ./nodemon.json ./
COPY ./tsconfig.json ./
COPY ./.env ./

VOLUME /urs/bin/src
VOLUME /urs/bin/data

RUN yarn; yarn compile

CMD ["yarn", "watch"]
